### PR TITLE
Added Chinese plugin information, changed style of checking allowed chars

### PR DESCRIPTION
**Pull request by berry64**
config.yml
StringUtils.java
CommandNovaGuilds.java

### CODE REVIEW

**Comment by MarcinWieczorek** [comment]
Thanks for contribution. 
I'm gonna review your changes. 
Did you check the efficiency of regular expressions and my old code? I'm going to test that first.

**Comment by MarcinWieczorek** [comment]
Performance tests:

``` ---------------------------------------------------------
Generating strings...
Generated 10000000 strings in 6.144s
---------------------------------------------------------
Testing Old method
Old method finished in 0.553s
---------------------------------------------------------
Testing New method
New method finished in 4.692s
---------------------------------------------------------
Difference:
4.139s
OLD method is faster
---------------------------------------------------------
```

**Comment by berry64** [comment]
The old method may be faster, but when i tried to use chinese/special unicode characters i cant, so by using the match way, i think i can use more characters

**Comment by berry64** [comment]
does the old method support special characters?
eg. chinese characters

**Comment by MarcinWieczorek** [comment]
Well, how would it be possible to match Chinese characters with the 'normal' alphabet?
Detecting disallowed characters wouldn't make sense, there's always a character you didn't list, there are too many... And I guess listing allowed Chinese characters is not possible as well.
Ideas?

**Comment by berry64** [comment]
maybe add a switch to config allowing users to use any characters?
so instead of checking, it returns true directly perhaps

**Comment by MarcinWieczorek** [comment]
Seems legit.

``` YAML
guild:
 stringchecking:
  enabled: true
  regex: false
  pattern: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
  regexpattern: "[A-Za-z0-9]*"
```

Let's connect both methods and add an 'off switch' like you said.
Wanna do it?
PS: change stringchecking to whatever, had no better idea.

**Comment by MarcinWieczorek** [comment]
Also, please make another pull request with your /ng translation, and I'm closing this one.

**Comment by berry64** [comment]
to the both methods: sure
to another pull request: done, created another one

**Pull request closed without merging**
