### PR TITLE
 Utility classes should not have public constructors

### PR DESCRIPTION
**Pull request by AymanDF**
This pull request is focused on resolving occurrences of Sonar rule squid:S1118 - “Utility classes should not have public constructors ”. You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1118
Please let me know if you have any questions.
Ayman Abdelghany.

### CODE REVIEW

**Comment by MarcinWieczorek** [comment]
Why do you use release/ prefix for such branches?

**Comment by AymanDF** [comment]
It's part of our process at DevFactory first we have a staging step to local git repo. and after reviewing the change it is released to github with release/ prefix.

**Comment by MarcinWieczorek** [comment]
It's misleading because I use that prefix because of git flow.

**Comment by AymanDF** [comment]
shall I remove the prefix from this branch?

**Comment by MarcinWieczorek** [comment]
feature/ or hotfix/ is fine. Check git flow out btw.

**Pull request merged**
